feat/OT-260-fix-categories-documentation
alkemyTech/OT260-Server pull request #121
Opened 2022-08-16 18:10 UTC by Jescobarmora

Added categories tag.
Added Authorization header.
Generate updated swagger.yaml file

2022-08-16 18:54 UTC, NataliaGatti approved these changes
Excelente Juan Andrés, justo recién probando veo que había quedado sin los tags
¡Muchas gracias!

2022-08-16 19:59 UTC, NataliaGatti requested changes

2022-08-16 19:59 UTC, NataliaGatti commented on app/controllers/api/v1/categories_controller.rb
> +        render json: CategorySerializer.new(@categories).serializable_hash, status: :ok
En el ticket especificaba que sólo se debía devolver el campo name de las mismas, creo que este cambio no aplicaría

2022-08-17 11:57 UTC, Jescobarmora commented on app/controllers/api/v1/categories_controller.rb
> +        render json: CategorySerializer.new(@categories).serializable_hash, status: :ok
Done =)

2022-08-17 13:13 UTC, NataliaGatti approved these changes

2022-08-17 15:49 UTC, lucas-perata approved these changes

2022-08-17 15:51 UTC, merged