OT260-15 The model, migrations and base controller were created
alkemyTech/OT260-Server pull request #16
Opened 2022-07-14 13:51 UTC by NataliaGatti

**The model, migrations and base controller were created**
There are two migrations, one for the Organization model and one for Discard softDeletes.
The fields of the model are:
1. The name which is a string and must exist to create a new organization.
2. The address which is a string and which need not exist to create a new organization.
3. The phone validates that it is a integer but it can be blank.
4. The email is a string and it has a format´s validation with regex. It can be blank.
5. The welcome_text is a text and must exist to create a new organization.
6. The about_us_text is a text and it´s need not exist to create a new organization.
7. It´s got a timestamps field which create automatically.
8. Discard was added in a second migration to apply softDeletes at the model.
9. The model allows to store an image.
Finally, the base controller was created without actions but even so the resources was created at routes.rb.
[Card OT260-15](https://alkemy-labs.atlassian.net/browse/OT260-15)

2022-07-14 20:24 UTC, FernandoCiballero commented on .env.sample
> -DB_HOST=
Sería conveniente no renombrar este archivo y crear un nuevo `.env`

2022-07-14 20:27 UTC, FernandoCiballero commented on .gitignore
> +/node_modules
Considero que no sería necesario agregarlo al gitignore, ya que no vamos a usar código javascript

2022-07-14 20:28 UTC, FernandoCiballero commented on config/routes.rb
> +  namespace :api, defaults: { format: :json } do
👏

2022-07-14 20:30 UTC, FernandoCiballero commented on config/routes.rb
> +      resources :organizations
Lo de agregar rutas no sería necesario en esta etapa ya que todavía no sabemos que endpoints vamos a tener.

2022-07-14 20:31 UTC, NataliaGatti commented on .gitignore
> +/node_modules
En ese caso, ¿directamente elimino la carpeta? 
Se me generó al ejecutar `yarn install` y no quería que se pusheara con el PR.

2022-07-14 20:33 UTC, FernandoCiballero commented on db/migrate/20220714124321_create_organizations.rb
> +    end
Podes agregar la migración de discard acá y nos ahorramos un archivo de migración:
```suggestion
  t.datetime :discarded_at
  t.index :discarded_at  
end
```

2022-07-14 20:35 UTC, FernandoCiballero commented on yarn.lock
> +
Idem con lo de node_modules

2022-07-14 20:36 UTC, FernandoCiballero requested changes
Muy bien Nati!! te deje unos comentarios.

2022-07-14 20:39 UTC, NataliaGatti commented on db/migrate/20220714124321_create_organizations.rb
> +    end
Listo, modificado el archivo de migración de creación de la tabla organizations y eliminado el de añadir los campos para discard.

2022-07-15 01:11 UTC, FernandoCiballero approved these changes
Muy bueno Nati 👏

2022-07-15 01:12 UTC, merged