OT260-20-Crear-modelo-migración-y-controlador-base-de-Testimonials
alkemyTech/OT260-Server pull request #20
Opened 2022-07-14 23:48 UTC by Silva-gonzalo

Crear modelo, migración y controlador base de Testimonials

Campos:
name: VARCHAR NOT NULL
content: VARCHAR NULLABLE
timestamps y softDeletes
El modelo puede o no tener una imagen, y se debera utilizar Active Storage

2022-07-15 02:39 UTC, FernandoCiballero commented on .env.sample
> +export DB_HOST= localhost
La idea es no modificar este archivo y crear uno nuevo llamado `.env`. En caso de que no funcionen las variables de entorno puede ejecutar en la terminal `spring stop`.

2022-07-15 02:40 UTC, FernandoCiballero commented on spec/requests/api/v1/testimonials_spec.rb
> +RSpec.describe 'Testimonials', type: :request do
```suggestion
RSpec.describe 'Api::V1::Testimonials', type: :request do
```

2022-07-15 02:43 UTC, FernandoCiballero requested changes
Muy bien Gonza!!! en principio fataria generar archivos correspondientes a los specs. Generalmente es más práctico general el controlador usando `rails g model Testimonial` para que te genere el spec de modelo y el Factory.

2022-07-17 19:47 UTC, Silva-gonzalo commented on spec/requests/api/v1/testimonials_spec.rb
> +RSpec.describe 'Testimonials', type: :request do
Perfecto ya subi la modificacion

2022-07-17 19:48 UTC, Silva-gonzalo commented on .env.sample
> +export DB_HOST= localhost
ya subí la corrección de este archivo

2022-07-17 22:58 UTC, FernandoCiballero commented on config/routes.rb
> +    	resources :testimonials
No sería necesario crear rutas en este ticket ya que no se solicita desarrollar ningun endpoint en específico.

2022-07-17 22:59 UTC, FernandoCiballero commented on db/migrate/20220713014358_create_testimonials.rb
> +    	t.string :name, null: false
Acá hay un error de indentación.
```suggestion
   t.string :name, null: false
```

2022-07-17 23:22 UTC, Silva-gonzalo commented on config/routes.rb
> +    	resources :testimonials
listo ya quedo modificado

2022-07-17 23:24 UTC, FernandoCiballero approved these changes
Muy bien Gonzalo!!! dejo un par de correciones con respecto a los specs ya que por ahora no vamos a tocar estos archivos, solo los dejamos como están por defecto. Más adelante nos toca ver tickets de test.

2022-07-17 23:25 UTC, merged