feat/OT260-42 - Endpoint Creación Categorías
alkemyTech/OT260-Server pull request #21
Opened 2022-07-15 13:35 UTC by lucas-perata

COMO usuario administrador
QUIERO agregar una categoría nueva al sistema
PARA categorizar las Novedades

Criterios de aceptación:
POST /categories - Deberá validar que se envíe el campo name, y el mismo sea un string

2022-07-17 23:41 UTC, FernandoCiballero commented on app/controllers/api/v1/categories_controller.rb
> +      # POST /categories
Se deben evitar lo más posible los comentarios de código en RoR.

2022-07-17 23:44 UTC, FernandoCiballero commented on app/controllers/api/v1/categories_controller.rb
> +        @category = Category.new(category_params)
Consulta: está checkeado que pasa si en el campo name envío otro tipo de dato que no sea string?

2022-07-17 23:45 UTC, FernandoCiballero requested changes
Dejo unos commentarios.

2022-07-18 00:00 UTC, lucas-perata commented on app/controllers/api/v1/categories_controller.rb
> +      # POST /categories
Perfecto. No lo sabía eso

2022-07-18 00:02 UTC, lucas-perata commented on app/controllers/api/v1/categories_controller.rb
> +        @category = Category.new(category_params)
Estaba pensando en eso. Ahora acepta cosas que no sean strings también. Para solucionarlo debería agregar `  validates_format_of :name, with: /[a-z]/, on: :create
`
en el modelo de category?

2022-07-25 01:30 UTC, merged