feat/OT-260-19: added model, migration and controller for news
alkemyTech/OT260-Server pull request #9
Opened 2022-07-13 18:26 UTC by gaston-amaya

[Ticket jira](https://alkemy-labs.atlassian.net/browse/OT260-19)

Tengo una duda, cuando hago las migraciones me da error pero es porque todavia no existe la tabla categories en la base de datos y no puede hacer la relacion, pero asumo que despues se va a resolver cuando todas las migraciones esten subidas

2022-07-13 22:17 UTC, FernandoCiballero commented on app/controllers/news_controller.rb
> +  # To Do
Además se si fijan en el archivo de rutas el controlador va dentro del namespace `api/v1` con lo cual el controlador debería encontrarse en la misma estructura.

2022-07-13 22:17 UTC, rquinterosv approved these changes

2022-07-13 22:20 UTC, FernandoCiballero commented on app/models/news.rb
> +  belongs_to :category
Te quedaría pendiente las validaciones, siempre es buena práctica si tener la mismas validadas las mismas restricciones de la DDBB. Ej para un `:name, null: false` debe hacer un `validates :name, presence: true`

2022-07-13 22:21 UTC, FernandoCiballero commented on db/migrate/20220713173921_create_news.rb
> +    end
Quedó pendiente el campo de discard.

2022-07-13 22:25 UTC, FernandoCiballero commented on db/migrate/20220713173921_create_news.rb
> +      t.references :category, foreign_key: true
```suggestion
      t.references :category, null: false, foreign_key: true 
```

2022-07-13 22:25 UTC, FernandoCiballero requested changes
Muy bien Gaston!!! te dejo unos comentarios.

2022-07-15 00:59 UTC, FernandoCiballero approved these changes
Muy Bueno Gaston!!! agregue los archivos de los specs que habian quedado pendientes. Siempre es recomendable usar en estos casos el `rails g model` y `rails g controller` para no olvidarse de ningun archivo.

2022-07-15 00:59 UTC, merged

2022-07-15 01:06 UTC, gaston-amaya commented
A dale perfecto! yo lo habia generado asi pero como no lo pedia entonces lo habia sacado